### PR TITLE
Get transaction command

### PR DESCRIPTION
**Pull request by Juan-M-V**
# What :computer: 
Add `get-transaction` command

# Why :hand:
To get transaction data by it's hash

# Evidence :camera:
```bash
$> npm run dev transaction get-transaction

> zksync-cli@0.0.0-development dev
> ts-node-esm src/index.ts transaction get-transaction

? Chain to use Local Dockerized node
? get transaction by hash 0xb89858c34996a2afc747c8161502d7e1cc12e341307dd5b18daa93bcd1168df6
{
  isL1Originated: false,
  status: 'verified',
  fee: '0x48b8f6b15880',
  gasPerPubdata: '0x4e20',
  initiatorAddress: '0xbd29a1b981925b94eec5c4f1125af02a2ec4d1ca',
  receivedAt: '2023-11-27T13:15:39.876Z',
  ethCommitTxHash: '0x244b08981b29170f53232251f37f7b2622c29121cb4b2d9e1f10b545d263039e',
  ethProveTxHash: '0x97b1e5fa39fcd9cf2444ddf934364cb8cf611e58b0b5aa60d5eab3d24146d373',
  ethExecuteTxHash: '0x035b4da51f436b4a33c689a2196ab40e6173c6bfcfde52e5bc13e185d1cc5cb1'
}
```

### CODE REVIEW

**Comment by JackHamer09** [comment]
@Juan-M-V could you please make sure that you added access to edit the PR for maintainers, cause for previous PRs it fails for me when I try to push any changes

**Comment by Juan-M-V** [comment]
> @Juan-M-V could you please make sure that you added access to edit the PR for maintainers, cause for previous PRs it fails for me when I try to push any changes

I wasn't able to change the settings for this PR. Is it okay if I close it and re-open it? I think I should be able to allow access when opening the PR

**Comment by JackHamer09** [comment]
@Juan-M-V I can create a new one myself, but yeah, in future would be good to have it right away :)

**Comment by Juan-M-V** [comment]
Will do!

**Comment by JackHamer09** [comment]
Moved to #122

**Pull request closed without merging**
