### PR TITLE
chore: remove ethers v5

### PR DESCRIPTION
**Pull request by jennyg0**
# What :computer: 
* removes ethers v5 from commands

# Why :hand:
* no longer supporting v5

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

### CODE REVIEW

**Comment by JackHamer09** [comment]
No strong opinion to not remove it, but most of our tools still use v5 😁

**Comment by JackHamer09** [comment]
I'm in favor in moving to viem instwad of upgrading to v6. Most of the industry is abandoning ethers because a lot of things are so much better in viem, including proper TS typings.

**Comment by itsacoyote** [comment]
> No strong opinion to not remove it, but most of our tools still use v5 😁

We can still maintain those projects, but probably a good idea to no longer support making new projects with v5?
As for viem, I think it would be a good switch, we can look into setting up a template for that.

**Comment by JackHamer09** [comment]
@itsacoyote  We already have viem templates but they are pretty outdated. They still use v1 viem but there was major update a while ago. Tho shouldn't be many changes for them templates

**Review by JackHamer09 — APPROVED** [review]

**Pull request merged**
