### PR TITLE
Feat: Add encode command

### PR DESCRIPTION
**Pull request by Juan-M-V**
# What 💻
add `encode` command to zksync-cli

# Why ✋
This will allow to encode a function call

# Evidence 📷

```bash
$> npm run dev contract encode
> zksync-cli@0.0.0-development dev
> ts-node-esm src/index.ts contract encode

? function to encode someFunction(address)
? arguments to encode 0x979a29A9347A773b2fB44D93D148D152ad9c23F0
0x1691d2bd000000000000000000000000979a29a9347a773b2fb44d93d148d152ad9c23f0
```

### CODE REVIEW

**Comment by JackHamer09** [comment]
@Juan-M-V please fill the description according to the default PR template to make it easier for everyone to understand what it is about

**Comment by JackHamer09** [comment]
> @Juan-M-V please fill the description according to the default PR template to make it easier for everyone to understand what it is about

@Juan-M-V

**Comment by Juan-M-V** [comment]
Sorry for the wait! I've updated the description

**Comment by JackHamer09** [comment]
Moved to #118

**Pull request closed without merging**
